apiVersion: v1
kind: Service
metadata:
  name: dangerous-heartbeat-service
  labels:
    app: dangerous-heartbeat
spec:
  selector:
    app: dangerous-heartbeat
  type: NodePort
  ports:
  - port: 8000          
    targetPort: 8000     
    nodePort: 30080    
